image:
  tag: 8.2-enterprise
ingress:
  enabled: true
  hosts:
    - name: sonarqube.ddns.net
  annotations:
    kubernetes.io/ingress.class: sonarqube
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - secretName: sonarqube-tls
      hosts:
        - sonarqube.ddns.net
resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
serviceAccount:
  create: true
  name: sonarqube
persistence:
  enabled: true
  storageClass: hostpath
elasticsearch:
  configureNode: false
postgresql:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
  serviceAccount:
    enabled: true
    name: sonarqube-postgresql
  volumePermissions:
    enabled: true
    securityContext:
      runAsUser: 1001
  shmVolume:
    chmod:
      enabled: false